### ISSUE TITLE
Need Help executing .cpp file using Xcode. 

### ISSUE THREAD

**Issue by Mohamed-Alguhiem** [cisc3620/6-intersections#4]
Hello, I am using Mac and I have XCode. I cloned the branch into a folder on my desktop but now I don't see a build folder included. I am trying to execute the code. Can someone tell me how to execute the .cpp file using Xcode?
Thanks.
@rivlev

**Comment by JessiicaWu** [comment]
It's different from the previous labs, you have to create a new project yourself.

**Comment by Mohamed-Alguhiem** [comment]
I did that and then when i run it. I don't get anything???

**Comment by rivlev** [comment]
There is no console output. It should write a file "intersections.out"

**Comment by J-A16** [comment]
there should be no console output? Not even a never intersects notification?

**Comment by J-A16** [comment]
@rivlev

**Comment by rivlev** [comment]
It will output to the console if there is no intersection. Otherwise it runs silently.

**Comment by J-A16** [comment]
Do I have an error if I'm only getting one intersection period from all of the tests?

**Comment by J-A16** [comment]
@rivlev
